# Het citeren van andere werken
Het citeren van werken van is belangrijk om fraude tegen te gaan, maar ook om je uitspraken meer geloofwaardig te laten overkomen. Hieronder staat een stuk tekst waar naar verschillende bronnen verwezen wordt.

Het maxima center in Utrecht houdt zich bezig met het onderzoeken en behandelen van kinderoncologie. Zo worden er verschillende technieken ontwikkeld en getest om een zo goed mogelijke behandeling te geven aan een patiënt. Zo was er in een onderzoek naar leukemie in kinderen een antilichaam gebruikt die DNA bindingen kan verbreken en de kankercellen dus dood gaan.[@brivioPhaseStudyInotuzumab2021]. Een andere techniek die gebruikt wordt is high-throughput screening (HTS). HTS is een techniek waarbij er een groot aantal stoffen getest in één keer getest kunnen worden. Dit levert grote hoeveelheden data op, en de kans van het vinden van een effectief medicijn wordt vergroot. Samen met verschillende fluorescentie technieken en kunnen er tot wel 100000 samples gescreend worden per dag [@liuTechnologicalAdvancesHighthroughput2004]. Hoewel er in het begin van de ontwikkeling van de HTS techniek vooral gezorgd werd om het aantal assays omhoog te krijgen, wordt er tegenwoordig vooral gekeken naar assays met meer fysiologische relevantie zodat er minder tests gedaan hoeven te worden en kosten lager kunnen worden[@mayrNovelTrendsHighthroughput2009]. Het prinses maxima center hebruikte HTS onder andere om een effectieve drug te vinden tegen acute myeloïde leukemie. De drug Pyrvinium pamoate bereikte een IC50 bij concentratie onder de 80 nM, en reduceerde cel groei en deling met 50% [@wanderHighthroughputDrugScreening2021].

Om HTS mogelijk te maken wordt bij het prinses maxima wordt gebruik gemaakt van het Beckman Coulter Biomek i7 Hybrid werkstation, waar het voorbereiden van de platen plaats vindt en er in grote snel- en nauwkeurigheid een 384 wells plaat gevuld kan worden [@HighthroughputScreening].  In de wells zitten verschillende soorten medicatie of controles, Het bijhouden van wat er in welke well zit werd tot op het heden met de hand in Excel gemaakt. Het maxima center vond dat dit makkelijker kon en heeft ons de opdracht gegeven om een app te maken waar deze informatie sneller en nauwkeuriger ingevoerd kan worden. Door gebruik te kunnen maken van de programmeertaal R wordt de app gemaakt met de shiny package. In de app zelf is het mogelijk om layouts up te loaden en deze aan te passen naar de huidige opzet. Zo kan de onder andere de drug, concentratie en de aanwezigheid van cellen aangepast worden. Met visualisatie plots is het mogelijk om deze aanpassing te zien en door de keuzes standaard te maken, worden fouten sneller voorkomen. Nadat alle aanpassing gemaakt zijn kan het bestand gedownload worden en staat de nieuwe data in een .CSV bestand.


